fullname = input('ป้อนชื่อ: ')
mid_score = input('ป้อนคะแนนกลางภาค: ')
final_score = input('ป้อนคะเเนนปลายภาค: ')
quiz_score = input('ป้อนคะเเนนเก็บ: ')
print('--------------------')
print(f'สวัสดีคุณ : {fullname}')
print(f'คุณสอบได้คะแนนรวม : {int(mid_score) + int(final_score) + int(quiz_score)} คะแนน')
print('--------------------')